#include	"allinc.h"

Settings::Settings()
{
	MAX_CHARS = DEFAULT_MAX_CHARS;
	CHARTIME = DEFAULT_CHARTIME;
	strcpy(LOGFILE, DEFAULT_LOGFILE);

	strcpy(TGA_FILE, DEFAULT_TGA_FILE);

	TGA_ID = DEFAULT_TGA_ID;
	TGA_PALETTE = DEFAULT_TGA_PALETTE;
	TGA_IMG_TYPE = DEFAULT_TGA_IMG_TYPE;
	TGA_PALETTE_START = DEFAULT_TGA_PALETTE_START;
	TGA_PALETTE_END = DEFAULT_TGA_PALETTE_END;
	TGA_PALETTE_SIZE = DEFAULT_TGA_PALETTE_SIZE;
	TGA_ORIGIN_X = DEFAULT_TGA_ORIGIN_X;
	TGA_ORIGIN_Y = DEFAULT_TGA_ORIGIN_Y;
	TGA_WIDTH = DEFAULT_TGA_WIDTH;
	TGA_HEIGHT = DEFAULT_TGA_HEIGHT;
	TGA_BITS_PER_PIXEL = DEFAULT_TGA_BITS_PER_PIXEL;
	TGA_ATTR = DEFAULT_TGA_ATTR;
}
